Found_Eng = float(input("score:"))
Gener_Bs = float(input("score:"))
Inter_Com_sys = float(input("score:"))
Com_Pro = float(input("score:"))
print("-------------- Your Score --------------")
print("Foundation English               :",Found_Eng)
print("General Business                 :",Gener_Bs)
print("Introduction to Computer Systems :",Inter_Com_sys)
print("Computer Programming             :",Com_Pro)
